# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BexioSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'code')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'access token')),
                ('expires_in', models.IntegerField(blank=True, null=True, verbose_name=b'expires in (seconds)')),
                ('token_type', models.CharField(default=b'Bearer', max_length=255, verbose_name=b'token type')),
                ('scope', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'scope')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'refresh token')),
                ('org', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'organization')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name=b'user id')),
            ],
        ),
    ]
